### ISSUE TITLE
Constant terraform drift on IAM membership

### ISSUE THREAD

**Issue by lra** [lacework/terraform-gcp-config#25]
Hi,

I have the following configuration defined:
```
module "gcp_organization_config" {
  source  = "lacework/config/gcp"
  version = "~> 1.0.2"

  org_integration = true
  organization_id = data.google_organization.whatever.org_id
  project_id      = "security-lacework-whatever"
}
```

It applies successfully:
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
But when I plan/apply right after, it shows a drift:
```
Terraform will perform the following actions:

  # module.gcp_organization_config.google_organization_iam_member.lacework_custom_organization_role_binding[0] will be updated in-place
  ~ resource "google_organization_iam_member" "lacework_custom_organization_role_binding" {
        id     = "123456789/organizations/123456789/roles/lwOrgComplianceRole/serviceAccount:lw-cfg-random@security-lacework-whatever.iam.gserviceaccount.com"
      # Warning: this attribute value will be marked as sensitive and will
      # not display in UI output after applying this change
      ~ member = (sensitive)
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes


Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
it applies nothing, and the drift is still there.

So terraform has a constant drift.

Versions used:
```
$ terraform version
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.67.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.1
+ provider registry.terraform.io/lacework/lacework v0.4.0
$ terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/google] ~> 3.67.0
├── provider[registry.terraform.io/lacework/lacework] ~> 0.4.0
├── module.gcp_organization_config
│   ├── provider[registry.terraform.io/hashicorp/random]
│   ├── provider[registry.terraform.io/lacework/lacework] ~> 0.2
│   ├── provider[registry.terraform.io/hashicorp/google] ~> 3.0
│   ├── provider[registry.terraform.io/hashicorp/time] ~> 0.6
│   └── module.lacework_cfg_svc_account
│       ├── provider[registry.terraform.io/hashicorp/google] ~> 3.0
│       └── provider[registry.terraform.io/hashicorp/random]
└── module.organization_level_audit_log
    ├── provider[registry.terraform.io/hashicorp/google] ~> 3.0
    ├── provider[registry.terraform.io/hashicorp/random]
    ├── provider[registry.terraform.io/hashicorp/time] ~> 0.6
    ├── provider[registry.terraform.io/lacework/lacework] ~> 0.2
    └── module.lacework_at_svc_account
        ├── provider[registry.terraform.io/hashicorp/random]
        └── provider[registry.terraform.io/hashicorp/google] ~> 3.0

Providers required by state:

    provider[registry.terraform.io/hashicorp/google]

    provider[registry.terraform.io/hashicorp/random]

    provider[registry.terraform.io/hashicorp/time]

    provider[registry.terraform.io/lacework/lacework]
```

**Comment by afiune** [comment]
@lra Thank you for your feedback! We just introduced support for Terraform 15+ so we are going to take a look at this ticket in the upcoming days, something we just noticed is that the behavior is coming from another module where we added the `sensitive` parameter here https://github.com/lacework/terraform-gcp-service-account/blob/main/output.tf#L19

**Comment by afiune** [comment]
**JIRA: ALLY-494**

**Comment by afiune** [comment]
Hello @lra - We started to work on this issue but unfortunately, we are unable to replicate the problem you are facing, we have added the exact code you shared with the same versions of providers and modules, and when we run `terraform plan` we do not see any drifts:

![Screen Shot 2021-06-01 at 3 06 53 PM](https://user-images.githubusercontent.com/5712253/120396202-6444bd00-c2f3-11eb-8b30-ce6e3151885c.png)

Is this a consistent behavior? Also, you are using a data source to get the org ID, could you try to put the id as a plain string instead? maybe this could be the problem of the drifts, for more information about "values that are not yet known" look at https://www.terraform.io/docs/language/expressions/references.html#values-not-yet-known where they mention something related to these resources:
> If unknown values are used in the configuration of a data resource, that data resource cannot be read during the plan phase and so it will be deferred until the apply phase. In this case, the results of the data resource will also be unknown values.

Let us know if there is anything we can help you with.

**Comment by afiune** [comment]
We are closing this ticket since we haven't had any activity for the past 14 days, if this is not fixed, feel free to re-open it.

Once again, thank you for your feedback!

**Comment by lra** [comment]
The drift is fixed by using all the latest versions.
